"""Add credits table

Revision ID: 47471bdf6b47
Revises: b41dbc30bc00
Create Date: 2025-02-12 14:16:33.042035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '47471bdf6b47'
down_revision: Union[str, None] = 'b41dbc30bc00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'credits',
        sa.Column('owner_id', UUID(as_uuid=True), sa.ForeignKey('users.id'), primary_key=True),
        sa.Column('total_credits', sa.Integer(), nullable=False),
        sa.Column('last_update', sa.DateTime(), default=sa.func.now(), onupdate=sa.func.now(), nullable=False)
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credits')
    # ### end Alembic commands ###
    
