services:
  backend:
    build: ./BackEndAPI
    container_name: backend
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://myuser:mypassword@db/mydb
      - IN_DOCKER=True
    volumes:
      - backend_logs:/app/logs  # Persistent logs for the API container
    depends_on:
      - db
      - rabbitmq

  pubapigw:
    build:
      context: ./PublicAPIGw
    container_name: pubapigw
    ports:
      - "8002:8002"
    environment:
      - IN_DOCKER=True
    volumes:
      - pubapigw_logs:/app/logs  # Persistent logs for the API container
    depends_on:
      - backend

  filemgrapi:
    build:
      context: ./FileMgrAPI
    container_name: filemgrapi
    ports:
      - "8003:8003"
    environment:
      - IN_DOCKER=True
    volumes:
      - filemgrapi_logs:/app/logs  # Persistent logs for the API container
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent database storage

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent RabbitMQ storage

  machine:
    build:
      context: ./machine
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=training
    depends_on:
      - rabbitmq
    deploy:
      replicas: 3

volumes:
  backend_logs:
    driver: local
  pubapigw_logs:
    driver: local
  filemgrapi_logs:
    driver: local
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
