"""Add credit transactions table

Revision ID: 08077ec77070
Revises: 47471bdf6b47
Create Date: 2025-02-12 14:35:28.539791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '08077ec77070'
down_revision: Union[str, None] = '47471bdf6b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transactions',
    sa.Column('id', UUID(as_uuid=True), nullable=False, primary_key=True, default=sa.text('uuid_generate_v4()')),
    sa.Column('owner_id', UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.Column('feature', sa.String(), nullable=False),  # Temporary field for now until the features are defined
    sa.CheckConstraint('amount > 0', name='check_amount_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id']),
    )
    op.create_index(op.f('ix_credit_transactions_id'), 'credit_transactions', ['id'], unique=False)
    op.alter_column('trainings', 'owner_id',
               existing_type=UUID(as_uuid=True),
               nullable=False)
    op.alter_column('trainings', 'dataset_id',
               existing_type=UUID(as_uuid=True),
               nullable=False)
    op.create_index(op.f('ix_trainings_id'), 'trainings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainings_id'), table_name='trainings')
    op.alter_column('trainings', 'dataset_id',
               existing_type=UUID(as_uuid=True),
               nullable=True)
    op.alter_column('trainings', 'owner_id',
               existing_type=UUID(as_uuid=True),
               nullable=True)
    op.drop_index(op.f('ix_credit_transactions_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    # ### end Alembic commands ###
