"""Add UUID relationship between users and datasets

Revision ID: 1f310152517e
Revises: f5826aee7321
Create Date: 2025-01-14 19:56:41.375221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '1f310152517e'
down_revision: Union[str, None] = 'f5826aee7321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('owner_id', UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'datasets', 'users', ['owner_id'], ['id'])
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.drop_column('datasets', 'owner_id')
    # ### end Alembic commands ###
