"""Add credit management transactions table

Revision ID: 2396dcb22e47
Revises: 08077ec77070
Create Date: 2025-02-12 15:20:05.742883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '2396dcb22e47'
down_revision: Union[str, None] = '08077ec77070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_management_transactions',
    sa.Column('transaction_id', UUID(as_uuid=True), nullable=False, primary_key=True, default=sa.text('uuid_generate_v4()')),
    sa.Column('owner_id', UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('external_reference', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed', 'reversed')", name='check_status'),
    sa.CheckConstraint("transaction_type IN ('credit_purchase', 'refund', 'manual_adjustment')", name='check_transaction_type'),
    sa.CheckConstraint('amount != 0', name='check_amount_nonzero'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id']),
    )
    op.create_index(op.f('ix_credit_management_transactions_transaction_id'), 'credit_management_transactions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_management_transactions_transaction_id'), table_name='credit_management_transactions')
    op.drop_table('credit_management_transactions')
    # ### end Alembic commands ###
