"""Add trainings table

Revision ID: b41dbc30bc00
Revises: 1f310152517e
Create Date: 2025-02-12 11:24:09.251729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = 'b41dbc30bc00'
down_revision: Union[str, None] = '1f310152517e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'trainings',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('base_model', sa.String(), nullable=False),
        sa.Column('imgs_count', sa.Integer(), nullable=False),
        sa.Column('time_taken', sa.Float(), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column('owner_id', UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('dataset_id', UUID(as_uuid=True), sa.ForeignKey('datasets.id'), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainings')
    # ### end Alembic commands ###
