"""Add generations table

Revision ID: e3839c2a4b23
Revises: 2396dcb22e47
Create Date: 2025-02-12 15:46:29.178425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = 'e3839c2a4b23'
down_revision: Union[str, None] = '2396dcb22e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generations',
    sa.Column('generation_id', UUID(as_uuid=True), nullable=False, primary_key=True, default=sa.text('uuid_generate_v4()')),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.Column('time_taken', sa.Float(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),  # Temporary field for now until the model is defined
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('owner_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id']),
    )
    op.create_index(op.f('ix_generations_generation_id'), 'generations', ['generation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generations_generation_id'), table_name='generations')
    op.drop_table('generations')
    # ### end Alembic commands ###
